#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/antrota
NAME=antrota
DESC="Antminer Shift Rota Daemon"
set -e

if [ ! -x "$DAEMON" ]
then
	echo "$DAEMON not found or not executable"
	exit 0
fi

do_start() {
	start-stop-daemon --start --exec "$DAEMON" --background
}

do_stop() {
	killall -9 "$NAME"
}
case "$1" in
  start)
        echo -n "Starting $DESC: "
	do_start
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
	do_stop
        echo "$NAME."
        ;;
  restart)
        echo -n "Restarting $DESC: "
        do_stop
        do_start
        echo "$NAME."
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0
